/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
import Image from '../components/Image';
import Quote from '../components/Quote';
import testComponent from '../components/testComponent';
import Text from '../components/Text';

const components = new Map();
components.set('Image', Image);
components.set('Quote', Quote);
components.set('testComponent', testComponent);
components.set('Text', Text);

export default function componentFactory(componentName) {
  return components.get(componentName);
};
