/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-config.js to modify the generation of this file.
export  function getConfig() {
  const config = {
  "sitecoreApiKey": "{16BA5138-5F02-47F1-A835-836407AB8812}",
  "sitecoreApiHost": "https://cm-master-mv2-test.velux.com",
  "jssAppName": "velux-marketing-cm",
  "sitecoreSiteName": "velux-marketing-cm",
  "defaultLanguage": "en",
  "graphQLEndpointPath": "/api/velux-marketing-cm",
  "appLanguages": [
    "en"
  ],
  "graphQLEndpoint": "https://cm-master-mv2-test.velux.com/api/velux-marketing-cm?sc_apikey={16BA5138-5F02-47F1-A835-836407AB8812}"
};

  if (typeof window !== 'undefined' && typeof window.__NUXT__ !== 'undefined' && typeof window.__NUXT__.jssConfig !== 'undefined') {
    Object.assign(config, window.__NUXT__.jssConfig);
  }

  return config;
}